spring:
  datasource:
    url: jdbc:mysql://localhost:3306/easy_tickets
    username: root
    password: pk0101PK
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    enabled: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: dev

server:
  port: 8080