spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/easy_tickets
    username: root
    password: pk0101PK
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    basic:
      enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081